--- drivers/net/wireless/Makefile
+++ drivers/net/wireless/Makefile
@@ -59,4 +59,6 @@
   obj-$(CONFIG_BCM4329)	+= bcm4329_204/
 endif
 
+obj-$(CONFIG_BCM4329)  += bcmdhd/
+
 obj-$(CONFIG_TIWLAN1251) += tiwlan1251/
